[project]
name = "cooking-compass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sanjay", email = "sanjay.05@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncmy>=0.2.14",
    "cryptography>=50.0.0",
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
cooking-compass = "cooking_compass:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
